/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.FileSystemResource;

import java.io.FileInputStream;
import java.util.Properties;

import static org.assertj.core.api.Assertions.assertThat;

// SpringにXXXResourceっていくつかあるけど、何？っていうやつです。
public class ResourceTest {
    @Test
    public void FileSystemResourceってなに() throws Exception {
        // フルパス指定で取得できる
        FileSystemResource フルパス = new FileSystemResource("/Users/ooguro/Documents/git/java-sandbox/sandbox/src/test/resources/test.txt");
        assertThat(フルパス.exists()).isTrue();

        // 相対パスで取得できる
        FileSystemResource 相対パス = new FileSystemResource("src/test/resources/test.txt");
        assertThat(相対パス.exists()).isTrue();

        // resourcesからの相対パスでは取得できない
        FileSystemResource resourcesからの相対パス = new FileSystemResource("test.txt");
        assertThat(resourcesからの相対パス.exists()).isFalse();
    }

    @Test
    public void ClassPathResourceってなに() throws Exception {
        // フルパス指定で取得できない
        ClassPathResource classPathResource = new ClassPathResource("/Users/ooguro/Documents/git/java-sandbox/sandbox/src/test/resources/test.txt");
        assertThat(classPathResource.exists()).isFalse();

        // resourcesからの相対パスで取得できる
        ClassPathResource xxx = new ClassPathResource("test.txt");
        assertThat(xxx.exists()).isTrue();
    }
}
